// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvFwuF3ywsM_7CUeCP6NPi1THhiNS3cKo',
    appId: '1:179045522471:web:5975dbc706f54e95470202',
    messagingSenderId: '179045522471',
    projectId: 'kochigo-app',
    authDomain: 'kochigo-app.firebaseapp.com',
    storageBucket: 'kochigo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGV30IKRe0QrjcXJC3TJ8lTmNffAkMLCo',
    appId: '1:179045522471:android:3d8d9b8cdbedd692470202',
    messagingSenderId: '179045522471',
    projectId: 'kochigo-app',
    storageBucket: 'kochigo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOivFwiXQfNZ8uD3q6f05qjc-68wEeRo0',
    appId: '1:179045522471:ios:54b259690fbb3392470202',
    messagingSenderId: '179045522471',
    projectId: 'kochigo-app',
    storageBucket: 'kochigo-app.firebasestorage.app',
    iosBundleId: 'com.kochigo.kochigoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOivFwiXQfNZ8uD3q6f05qjc-68wEeRo0',
    appId: '1:179045522471:ios:54b259690fbb3392470202',
    messagingSenderId: '179045522471',
    projectId: 'kochigo-app',
    storageBucket: 'kochigo-app.firebasestorage.app',
    iosBundleId: 'com.kochigo.kochigoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvFwuF3ywsM_7CUeCP6NPi1THhiNS3cKo',
    appId: '1:179045522471:web:115df1947628e33c470202',
    messagingSenderId: '179045522471',
    projectId: 'kochigo-app',
    authDomain: 'kochigo-app.firebaseapp.com',
    storageBucket: 'kochigo-app.firebasestorage.app',
  );

}